# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('act_id', models.AutoField(primary_key=True, serialize=False)),
                ('act_name', models.CharField(max_length=100)),
                ('act_content', models.TextField()),
                ('true_content', models.TextField()),
            ],
            options={
                'db_table': 'activity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('news_id', models.AutoField(primary_key=True, serialize=False)),
                ('news_date', models.DateField()),
                ('title', models.CharField(max_length=20)),
                ('news_content', models.TextField()),
                ('picture_path', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'news',
                'managed': False,
            },
        ),
    ]
