# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 09:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActMoney',
            fields=[
                ('actmoney_id', models.AutoField(primary_key=True, serialize=False)),
                ('payer_name', models.CharField(max_length=10)),
                ('pay_money', models.IntegerField()),
                ('pay_date', models.DateField()),
            ],
            options={
                'db_table': 'act_money',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MoneyCount',
            fields=[
                ('mc', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='finance.ActMoney')),
                ('money_count', models.IntegerField()),
            ],
            options={
                'db_table': 'money_count',
                'managed': False,
            },
        ),
    ]
