# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Daily',
            fields=[
                ('daily_id', models.AutoField(primary_key=True, serialize=False)),
                ('create_date', models.DateField()),
                ('update_date', models.DateField()),
                ('content', models.TextField()),
                ('status', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'daily',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('part_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('part_name', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'department',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('emp_pass', models.CharField(max_length=100)),
                ('auth', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=10)),
                ('sex', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'employee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('beds', models.IntegerField()),
            ],
            options={
                'db_table': 'room',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TempEmployee',
            fields=[
                ('emp_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('emp_pass', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=10)),
                ('sex', models.CharField(max_length=2)),
                ('job', models.CharField(max_length=100)),
                ('adress', models.CharField(max_length=100)),
                ('in_date', models.DateField()),
                ('child_yn', models.CharField(max_length=2)),
                ('date_count', models.SmallIntegerField()),
                ('id_card', models.CharField(max_length=20)),
                ('out_date', models.DateField()),
                ('remark', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'temp_employee',
                'managed': False,
            },
        ),
    ]
