# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('repair_id', models.AutoField(primary_key=True, serialize=False)),
                ('repair_type', models.CharField(max_length=10)),
                ('detail', models.TextField(blank=True, null=True)),
                ('repair_date', models.DateField()),
                ('repair_status', models.CharField(max_length=10)),
                ('send_date', models.DateField()),
                ('follow_date', models.DateField()),
                ('finish_date', models.DateField()),
            ],
            options={
                'db_table': 'repair',
                'managed': False,
            },
        ),
    ]
