# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 09:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('commodity_id', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('commodity_name', models.CharField(max_length=100)),
                ('commodity_type', models.CharField(max_length=100)),
                ('count', models.IntegerField()),
                ('unit', models.CharField(max_length=10)),
                ('remark', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'commodity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InEntrepot',
            fields=[
                ('ie_id', models.AutoField(primary_key=True, serialize=False)),
                ('ie_date', models.DateField()),
            ],
            options={
                'db_table': 'in_entrepot',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OutEntrepot',
            fields=[
                ('oe_id', models.AutoField(primary_key=True, serialize=False)),
                ('oe_date', models.DateField()),
            ],
            options={
                'db_table': 'out_entrepot',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InEntrepotDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ie', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='entrepot.InEntrepot')),
                ('ie_count', models.IntegerField()),
                ('unit', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'in_entrepot_detail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OutEntrepotDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oe', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='entrepot.OutEntrepot')),
                ('oe_count', models.IntegerField()),
                ('unit', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'out_entrepot_detail',
                'managed': False,
            },
        ),
    ]
